export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_LOGIN_LIST = 'EVENT_LOGIN_LIST';
export const ARRIVAL_LIST ='ARRIVAL_LIST';
export const DEPARTURE_LIST = 'DEPARTURE_LIST';
export const STAY_LIST = 'STAY_LIST';
export const UPLOAD_ID_PROOF_LIST = 'UPLOAD_ID_PROOF_LIST';
export const DOWNLOAD_ID_PROOF_LIST = 'DOWNLOAD_ID_PROOF_LIST';
export const DELETE_ID_PROOF_LIST = 'DELETE_ID_PROOF_LIST';