export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_LOGIN_LIST = 'EVENT_LOGIN_LIST';
export const ARRIVAL_LIST ='ARRIVAL_LIST';
export const DEPARTURE_LIST = 'DEPARTURE_LIST';
export const UPLOAD_ID_PROOF_LIST = 'UPLOAD_ID_PROOF_LIST';